language: lua

before_install:
  - sudo apt-get update
  - sudo apt-get install -y luarocks libssl-dev git
  - sudo luarocks install luabitop
  - sudo luarocks install busted
  - sudo luarocks install luasec OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu

script: busted -e 'package.path="./?/init.lua;./?.lua;"..package.path' tests/spec/*.lua