language: lua

before_install:
  - sudo apt-get update
  - sudo apt-get install -y luarocks libssl-dev git
  - sudo luarocks install luasec
  - sudo luarocks install luasocket
  - sudo luarocks install luabitop
  - sudo luarocks install busted

script: busted -e 'package.path="./?/init.lua;./?.lua;"..package.path' tests/spec/*.lua