language: lua

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libssl-dev git
  - sudo pip install hererocks

script:
  ./tests/run-for-all-lua-versions.sh

notifications:
  email:
    on_success: change
    on_failure: always
