language: lua

before_install:
  sudo apt-get update
  sudo apt-get install -y luarocks
  sudo luarocks install busted

script: busted -e 'package.path="./?/init.lua;./?.lua;"..package.path' tests/spec/*.lua